### ISSUE TITLE
issues with the upcoming version of scales

### ISSUE THREAD

**Issue by thomasp85** [animint/animint2#109]
Hi, we are in the process of releasing a new version of scales. Our reverse dependency checks show issues with animint2. 

    ```
    Running examples in ‘animint2-Ex.R’ failed
    The error most likely occurred in:
    
    > ### Name: geom_freqpoly
    > ### Title: Histograms and frequency polygons.
    > ### Aliases: geom_freqpoly geom_histogram stat_bin
    > 
    > ### ** Examples
    > 
    > ggplot(diamonds, aes(carat)) +
    ...
    + # You can also transform the y axis.  Remember that the base of the bars
    + # has value 0, so log transformations are not appropriate
    + m <- ggplot(movies, aes(x = rating))
    + m + geom_histogram(binwidth = 0.5) + scale_y_sqrt()
    + }
    Loading required package: ggplot2movies
    Error in if (zero_range(as.numeric(limits))) { : 
      missing value where TRUE/FALSE needed
    Calls: <Anonymous> ... train_cartesian -> <Anonymous> -> f -> <Anonymous> -> f
    Execution halted
    ```

I'd have liked to provide some guidance on fixing this but the heavy inlining and overwriting of the ggplot2 namespace in the package makes it non-trivial. I hope you can find the cause. We plan to submit scales in 2 weeks

**Comment by tdhock** [comment]
hi, thanks for the info.
it seems like the issue comes from this note in scales NEWS.md:
```
* `transform_sqrt()` no longer returns an inverse for values outside of its 
  domain (#214)
```
In that example, the issue results from the use of `scale_y_sqrt`. Inside ScaleContinuous get_breaks method, `self$trans$inverse(limits)` is called. Using CRAN scales I get `-0.3122499  6.5572479` as the result, whereas using scales from github I get `NA 42.9975` (missing value instead of finite negative value). The issue comes from passing the NA to scales::zero_range, which returns NA in that case. The code `if (zero_range(as.numeric(limits))) { :` gives an error because the argument to if should be TRUE or FALSE (not NA). 
There are several instances of this pattern (zero_range inside if) in ggplot2 code, https://github.com/search?q=repo%3Atidyverse%2Fggplot2%20zero_range&type=code which could be problematic (will error if zero_range returns NA).
So I believe the fix should be to change these if statements, to make sure the argument is either TRUE or FALSE (not NA), do you agree?
If so, could please change zero_range so that it always returns TRUE or FALSE?
Otherwise, what change would you suggest to fix?
Thanks in advance!

One way to do that would be to edit

**Comment by thomasp85** [comment]
The issue is that you have inlined a very old version of ggplot2 which doesn't respond well to the changes in scales. The ggplot2 code has been updated numerous times since then and e.g. now squishes the limits to the domain before calculating the inverse. `zero_range()` behaves as advertised when it comes to handling `NA` values so that will not change.

Your best course of action is probably to make your inlined code current with ggplot2 (this is however a moving target which it is so hard to maintain inlining a huge library), or fix the get_breaks code surgically, inspired by what we do in ggplot2

**Comment by tdhock** [comment]
That is useful to know about "squishes the limits to the domain before calculating the inverse."
That is strange to hear that you do not want to fix the potential for error with the if(zero_range) pattern.
For the purposes of CRAN check, we can fix this issue by deleting the example which caused it.

**Comment by thomasp85** [comment]
The places where it is used we already have guards around what values can come out so there is no real venue for issues in the current ggplot2 codebase
