### ISSUE TITLE
Nhi GSOC'24 progress

### ISSUE THREAD

**Issue by tdhock** [animint/animint2#128]
@nhintruong I was expecting to see what you are working on for GSOC'24 in issues/PRs/blogs, with updates at least once per day. Can you please write what you worked on every day on this issue?
@Faye-yufan @siddhesh195 are also involved with GSOC'24

**Comment by tdhock** [comment]
hi @nhintruong it has been about 2 weeks and still you have not written any daily progress reports. What are you working on? If you do not share what you are working on every day in GSOC, then you will not pass the evaluations.

**Comment by tdhock** [comment]
here is an example of what I expect https://github.com/Nj221102/data.table-gSoc-24-project/issues/1

**Comment by nhintruong** [comment]
Hi @tdhock and @Faye-yufan, I will be documenting my progress on the GSoC'24 tasks in this GitHub issue

06/23/2024: 

1. Visualization Task Porting:

- I've encountered some challenges due to missing files, which I mentioned in our current meeting. To address this, I've created GitHub Issue in the repository of each source code and mentioned Toby for guidance. 
 tdhock/sandia-enrollment/issues/1 
tdhock/species-variable-selection/issues/1

2. Chromote Testing Task: 

- I've updated the workflow in my repository which I forked from animint/animint 2, transitioning the use of Firefox (which I initially believed to be PhantomJS) to Chrome. 
- After running the updated workflow, I identified 3 test suites that failed. Please find the results of each test suite below:

Test Suite renderer1 (FAIL 25 | WARN 0 | SKIP 0 | PASS 427) 
![image](https://github.com/animint/animint2/assets/102540257/e0f4e41e-e41d-497b-bdb0-d61b31eeb5a5)

Test Suite renderer2 (FAIL 11 | WARN 0 | SKIP 0 | PASS 185)
![image](https://github.com/animint/animint2/assets/102540257/0f1c17e5-abe1-4452-a92e-92ab0fedc0a2)

Test Suite renderer3 (FAIL 7 | WARN 0 | SKIP 0 | PASS 66)
![image](https://github.com/animint/animint2/assets/102540257/c9ca9711-8cbb-4072-ae59-273ec9911024)

**Comment by tdhock** [comment]
closing in favor of #136
