### ISSUE TITLE
Gallery task: Writing automatic script to download R codes linked to examples on NAU rcdata server

### ISSUE THREAD

**Issue by nhintruong** [animint/animint2#132]
According to my proposal, my task includes writing an automatic script to download R codes linked to examples on NAU rcdata server, which entails crawling the linked R codes. To achieve this, I am following this [web crawling tutorial](https://ladal.edu.au/webcrawling.html).

@Faye-yufan I would be sincerely grateful if you could review this tutorial and provide feedback on my approach. Could you please advise if this approach seems appropriate and suggest any improvements or adjustments I can make with my task? 

Thank you very much for your time and assistance.

**Comment by tdhock** [comment]
Like I said earlier, I don't think web crawling will be fruitful, because each of the data viz source links are different, so you should not expect to be able to just do a for loop over all of them, and get a rendered data viz in each case. Instead, I think you should look at each data viz one by one, and copy/modify the source code, to make it work with the new animint2pages function (basically just make sure to add a `source` link)

**Comment by tdhock** [comment]
if that is ok, please close

**Comment by nhintruong** [comment]
Thank you very much for your feedback, Toby. I will close this Issue.
