### ISSUE TITLE
Improved Documentation and Find Bugs

### ISSUE THREAD

**Issue by biplab-sutradhar** [animint/animint2#157]
Before:
![image](https://github.com/user-attachments/assets/2e7c3932-33fc-4cb5-951b-528d8c690ea1)

After:
![image](https://github.com/user-attachments/assets/c32e6def-1928-4083-8920-1b580c3b0dab)

Changes Made:
Added border, shadow, and hover effects to the navigation bar 
Applied padding to inner ul elements for better spacing.

Issues:
The documentation hasn't been updated since 2023-06-11.
In mobile view, the navigation bar moves to the bottom. It should either remain at the top or be collapsible for better accessibility.
This documentation is generated by pkgdown, so it is tough to control UI @tdhock  can you give some suggestion

**Comment by ampurr** [comment]
Hey, Biplab! I confess I have mixed feelings on the specific UI changes you're making, but that's up to Toby, not me; and in any case I'm glad you're working on the website. This makes us website buddies. 😄

Addressing the issues one by one:

1. Yeah, you gotta manually build the website with `pkgdown` and then commit. The alternative (which I'll get around to one of these centuries if no one else does) is to set up a CI/CD pipeline so that the site automatically builds upon a relevant commit. You can do that if you want.
2. That's an artifact of `pkgdown`, unfortunately. There's no easy way to shunt the TOC to the top. Nor is there an easy way to wrap `<details>` around it.
  - The easiest way to push the TOC to the top probably involves flexbox's `flex-direction`, `<main>`, and `<aside>`.
  - The easiest way to wrap `<details>` around the TOC probably involves building the website and then modifying the resulting HTML document.
3. What specific UI control struggles are you having? In general, you'd edit the `pkgdown/extra.css` file.

**Comment by ampurr** [comment]
I think the cleanest way to resolve this problem is to bring it up in the [pkgdown Github](https://github.com/r-lib/pkgdown/). Maybe offer to make a pull request. If `pkgdown` changes how they do TOC, then it'll trickle down to our website.

It's also possible that they solved this problem in a `pkgdown` version and it's not trickled down cuz we haven't updated the site in a while. Did you re-render the site via `pkgdown`? I'd do that first to check. 👀

Sorry, I'm not sure what you mean when you ask if the documentation can be "dynamic and controlled using html, css, js or any library." Could you clarify? 😅

If you're asking if you can customize the site with HTML, CSS, or JS: yes, absolutely. Take a look at the [pkgdown documentation](https://pkgdown.r-lib.org/articles/customise.html#additional-html-and-files).

**Comment by biplab-sutradhar** [comment]
@ampurr sorry for late reply 
I tried to generate website for this repo using the latest version of pkgdown 2.1.1. Things did not change, but in their main docs https://pkgdown.r-lib.org/, they have implemented dark and light mode, which I can also implement on the animint website😅

**Comment by tdhock** [comment]
> I think the cleanest way to resolve this problem is to bring it up in the [pkgdown Github](https://github.com/r-lib/pkgdown/). Maybe offer to make a pull request. If pkgdown changes how they do TOC, then it'll trickle down to our website.

yes this is the right approach (first consult their docs, then file an issue if necessary).

please make a PR to improve the documentation on the web site, it would be much appreciated.

**Comment by biplab-sutradhar** [comment]
@tdhock should I create a pr for whole updated docs  before making other feature updates and when I generated pages then only homepage means authors list updated(data from description) but other pages like Changelog (data from news.md) are not updating.

**Comment by tdhock** [comment]
best is lots of small PRs with minimal amount of changes to review. (but don't break related changes into separate PRs)
first pr would be to just re-make the website with current pkgdown.
next would be any other changes.

**Comment by ampurr** [comment]
> @ampurr sorry for late reply I tried to generate website for this repo using the latest version of pkgdown 2.1.1. Things did not change, but in their main docs https://pkgdown.r-lib.org/, they have implemented dark and light mode, which I can also implement on the animint website 😅

No need to apologize. A day is not late. In any case, you don't owe me a response. :>

Oh, sweet. Yeah, if you re-render the site, we'll get light and dark mode (as you said).

**Comment by biplab-sutradhar** [comment]
@tdhock  during the re rendering of this website only the homepage which includes the authors list (data from the description), is being generated other pages like the changelog (data from news.md) and reference files are not generating what am I missing? I am thinking of creating a pr at least after generating all the files.

**Comment by ampurr** [comment]
@biplab-sutradhar, could you copy/paste the code you used to render the site? Any warning messages or anything like that?

**Comment by biplab-sutradhar** [comment]
@ampurr I am not updating any code just cloned current repo and it is running but except  the homepage other pages not rendering.

 URLs ok.
✔ Favicons ok.
✔ Open graph metadata ok.
✔ Articles metadata ok.
✖ Reference metadata not ok.
  In _pkgdown.yml, 1 topic missing from index: "update_gallery".
  Either use `@keywords internal` to drop from index, or
── Initialising site ───────────────────────────────────────────────────────────
── Building home ───────────────────────────────────────────────────────────────
Writing authors.html
Reading readme_website.md
Writing readme_website.html
Reading README.md
Writing index.html
Writing 404.html
── Building function reference ─────────────────────────────────────────────────
Error: 
! in callr subprocess.
Caused by error in `build_reference_index(pkg)`:
! In _pkgdown.yml, 1 topic missing from index: "update_gallery".
ℹ Either use `@keywords internal` to drop from index, or
ℹ See `$stdout` and `$stderr` for standard output and error.
Type .Last.error to see the more details.
Warning message:
In readLines(con, warn = readLines.warn) :
  incomplete final line found on './_pkgdown.yml'
> pkgdown::preview_site()
ℹ Previewing site
Warning message:
In readLines(con, warn = readLines.warn) :
  incomplete final line found on './_pkgdown.yml'
>

**Comment by tdhock** [comment]
I think this means we need to either document or mark as internal the new function update_gallery() which I believe was added since the last pkgdown web site update

**Comment by ampurr** [comment]
Okay, marked the new function as internal & threw it into a PR.
