### ISSUE TITLE
Review Animint Gallery

### ISSUE THREAD

**Issue by biplab-sutradhar** [animint/animint2#178]
@tdhock I created gallery can you please check it https://biplab-sutradhar.github.io/gallery/
code for visualization https://github.com/biplab-sutradhar/gallery/blob/main/README.md
code for gallery https://github.com/biplab-sutradhar/gallery/tree/master 
can I add directly link here https://github.com/rstats-gsoc/gsoc2025/wiki/Animated-interactive-ggplots

**Comment by tdhock** [comment]
ok that is a good start. 
![image](https://github.com/user-attachments/assets/c2c9a79a-8472-4b93-a18d-f08ba6e3bbff)
I see you changed the background color and number of columns. That is not necessary, and in fact detrimental because your gallery is missing links to R source code used to make each viz, can you add that please?
you can use the same template/html as the main gallery, which looks as below.
![image](https://github.com/user-attachments/assets/8756b853-a983-4f13-8d89-6183a494db68)

**Comment by tdhock** [comment]
yes please add your links to the gsoc page if you want to be considered as a gsoc'25 contributor.
